/**
 * This class is generated by jOOQ
 */
package no.rightcloud.demo.author.jooq.packages;


import javax.annotation.Generated;

import no.rightcloud.demo.author.jooq.Devdata;
import no.rightcloud.demo.author.jooq.packages.user_grant.Granttoroles;

import org.jooq.Configuration;
import org.jooq.impl.PackageImpl;


/**
 * Convenience access to all stored procedures and functions in USER_GRANT
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGrant extends PackageImpl {

    private static final long serialVersionUID = -1669715514;

    /**
     * The reference instance of <code>DEVDATA.USER_GRANT</code>
     */
    public static final UserGrant USER_GRANT = new UserGrant();

    /**
     * Call <code>DEVDATA.USER_GRANT.GRANTTOROLES</code>
     */
    public static void granttoroles(Configuration configuration) {
        Granttoroles p = new Granttoroles();

        p.execute(configuration);
    }

    /**
     * No further instances allowed
     */
    private UserGrant() {
        super("USER_GRANT", Devdata.DEVDATA);
    }
}
