/**
 * This class is generated by jOOQ
 */
package no.rightcloud.demo.pay.jooq.packages.user_grant;


import javax.annotation.Generated;

import no.rightcloud.demo.pay.jooq.Devdata;
import no.rightcloud.demo.pay.jooq.packages.UserGrant;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Granttoroles extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 839000332;

    /**
     * Create a new routine call instance
     */
    public Granttoroles() {
        super("GRANTTOROLES", Devdata.DEVDATA, UserGrant.USER_GRANT);
    }
}
