/**
 * This class is generated by jOOQ
 */
package no.rightcloud.demo.pay.jooq;


import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in DEVDATA
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>DEVDATA.AUTHOR_SEQ</code>
     */
    public static final Sequence<BigInteger> AUTHOR_SEQ = new SequenceImpl<BigInteger>("AUTHOR_SEQ", Devdata.DEVDATA, org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false));
}
