
CREATE TABLE AUTHOR (
  ID NUMBER(20,0),
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50)
);

CREATE SEQUENCE AUTHOR_SEQ START WITH 1 INCREMENT BY 1 CACHE 100;

BEGIN
   user_grant.granttoroles;
END;
/