/**
 * This class is generated by jOOQ
 */
package no.rightcloud.demo.author.jooq.tables.records;


import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;

import javax.annotation.Generated;

import no.rightcloud.demo.author.jooq.tables.PmtInfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PmtInfoRecord extends UpdatableRecordImpl<PmtInfoRecord> implements Record18<BigInteger, BigInteger, String, BigDecimal, BigDecimal, BigDecimal, String, Date, String, String, String, String, String, String, BigDecimal, String, String, String> {

    private static final long serialVersionUID = -1507070982;

    /**
     * Setter for <code>DEVDATA.PMT_INFO.PMT_INFO_ID</code>.
     */
    public void setPmtInfoId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.PMT_INFO_ID</code>.
     */
    public BigInteger getPmtInfoId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.FK_PMT_HEAD_ID</code>.
     */
    public void setFkPmtHeadId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.FK_PMT_HEAD_ID</code>.
     */
    public BigInteger getFkPmtHeadId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.PMT_METHOD</code>.
     */
    public void setPmtMethod(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.PMT_METHOD</code>.
     */
    public String getPmtMethod() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.BATCH_BOOKING</code>.
     */
    public void setBatchBooking(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.BATCH_BOOKING</code>.
     */
    public BigDecimal getBatchBooking() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.NR_OF_TRANS</code>.
     */
    public void setNrOfTrans(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.NR_OF_TRANS</code>.
     */
    public BigDecimal getNrOfTrans() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.CTRL_SUM</code>.
     */
    public void setCtrlSum(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.CTRL_SUM</code>.
     */
    public BigDecimal getCtrlSum() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.INSTR_PRTY</code>.
     */
    public void setInstrPrty(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.INSTR_PRTY</code>.
     */
    public String getInstrPrty() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.REQD_EXCTN_DT</code>.
     */
    public void setReqdExctnDt(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.REQD_EXCTN_DT</code>.
     */
    public Date getReqdExctnDt() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DEBTOR_NAME</code>.
     */
    public void setDebtorName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DEBTOR_NAME</code>.
     */
    public String getDebtorName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_POSTCODE</code>.
     */
    public void setDbtrPostcode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_POSTCODE</code>.
     */
    public String getDbtrPostcode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_TOWNNAME</code>.
     */
    public void setDbtrTownname(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_TOWNNAME</code>.
     */
    public String getDbtrTownname() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_CTRY</code>.
     */
    public void setDbtrCtry(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_CTRY</code>.
     */
    public String getDbtrCtry() {
        return (String) get(11);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_POSTADR1</code>.
     */
    public void setDbtrPostadr1(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_POSTADR1</code>.
     */
    public String getDbtrPostadr1() {
        return (String) get(12);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_POSTADR2</code>.
     */
    public void setDbtrPostadr2(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_POSTADR2</code>.
     */
    public String getDbtrPostadr2() {
        return (String) get(13);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_ORG_ID</code>.
     */
    public void setDbtrOrgId(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_ORG_ID</code>.
     */
    public BigDecimal getDbtrOrgId() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_ACCNT</code>.
     */
    public void setDbtrAccnt(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_ACCNT</code>.
     */
    public String getDbtrAccnt() {
        return (String) get(15);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_ACCNT_CCY</code>.
     */
    public void setDbtrAccntCcy(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_ACCNT_CCY</code>.
     */
    public String getDbtrAccntCcy() {
        return (String) get(16);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INFO.DBTR_AGENT_BIC</code>.
     */
    public void setDbtrAgentBic(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INFO.DBTR_AGENT_BIC</code>.
     */
    public String getDbtrAgentBic() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<BigInteger, BigInteger, String, BigDecimal, BigDecimal, BigDecimal, String, Date, String, String, String, String, String, String, BigDecimal, String, String, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<BigInteger, BigInteger, String, BigDecimal, BigDecimal, BigDecimal, String, Date, String, String, String, String, String, String, BigDecimal, String, String, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return PmtInfo.PMT_INFO.PMT_INFO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return PmtInfo.PMT_INFO.FK_PMT_HEAD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PmtInfo.PMT_INFO.PMT_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return PmtInfo.PMT_INFO.BATCH_BOOKING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return PmtInfo.PMT_INFO.NR_OF_TRANS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return PmtInfo.PMT_INFO.CTRL_SUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PmtInfo.PMT_INFO.INSTR_PRTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return PmtInfo.PMT_INFO.REQD_EXCTN_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return PmtInfo.PMT_INFO.DEBTOR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return PmtInfo.PMT_INFO.DBTR_POSTCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return PmtInfo.PMT_INFO.DBTR_TOWNNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return PmtInfo.PMT_INFO.DBTR_CTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return PmtInfo.PMT_INFO.DBTR_POSTADR1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return PmtInfo.PMT_INFO.DBTR_POSTADR2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return PmtInfo.PMT_INFO.DBTR_ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return PmtInfo.PMT_INFO.DBTR_ACCNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return PmtInfo.PMT_INFO.DBTR_ACCNT_CCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return PmtInfo.PMT_INFO.DBTR_AGENT_BIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getPmtInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getFkPmtHeadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPmtMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getBatchBooking();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getNrOfTrans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getCtrlSum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInstrPrty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getReqdExctnDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDebtorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDbtrPostcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDbtrTownname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDbtrCtry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getDbtrPostadr1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getDbtrPostadr2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getDbtrOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getDbtrAccnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getDbtrAccntCcy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getDbtrAgentBic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value1(BigInteger value) {
        setPmtInfoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value2(BigInteger value) {
        setFkPmtHeadId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value3(String value) {
        setPmtMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value4(BigDecimal value) {
        setBatchBooking(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value5(BigDecimal value) {
        setNrOfTrans(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value6(BigDecimal value) {
        setCtrlSum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value7(String value) {
        setInstrPrty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value8(Date value) {
        setReqdExctnDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value9(String value) {
        setDebtorName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value10(String value) {
        setDbtrPostcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value11(String value) {
        setDbtrTownname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value12(String value) {
        setDbtrCtry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value13(String value) {
        setDbtrPostadr1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value14(String value) {
        setDbtrPostadr2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value15(BigDecimal value) {
        setDbtrOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value16(String value) {
        setDbtrAccnt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value17(String value) {
        setDbtrAccntCcy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord value18(String value) {
        setDbtrAgentBic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInfoRecord values(BigInteger value1, BigInteger value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, String value7, Date value8, String value9, String value10, String value11, String value12, String value13, String value14, BigDecimal value15, String value16, String value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PmtInfoRecord
     */
    public PmtInfoRecord() {
        super(PmtInfo.PMT_INFO);
    }

    /**
     * Create a detached, initialised PmtInfoRecord
     */
    public PmtInfoRecord(BigInteger pmtInfoId, BigInteger fkPmtHeadId, String pmtMethod, BigDecimal batchBooking, BigDecimal nrOfTrans, BigDecimal ctrlSum, String instrPrty, Date reqdExctnDt, String debtorName, String dbtrPostcode, String dbtrTownname, String dbtrCtry, String dbtrPostadr1, String dbtrPostadr2, BigDecimal dbtrOrgId, String dbtrAccnt, String dbtrAccntCcy, String dbtrAgentBic) {
        super(PmtInfo.PMT_INFO);

        set(0, pmtInfoId);
        set(1, fkPmtHeadId);
        set(2, pmtMethod);
        set(3, batchBooking);
        set(4, nrOfTrans);
        set(5, ctrlSum);
        set(6, instrPrty);
        set(7, reqdExctnDt);
        set(8, debtorName);
        set(9, dbtrPostcode);
        set(10, dbtrTownname);
        set(11, dbtrCtry);
        set(12, dbtrPostadr1);
        set(13, dbtrPostadr2);
        set(14, dbtrOrgId);
        set(15, dbtrAccnt);
        set(16, dbtrAccntCcy);
        set(17, dbtrAgentBic);
    }
}
