/**
 * This class is generated by jOOQ
 */
package no.rightcloud.demo.author.jooq.tables.records;


import java.math.BigDecimal;
import java.math.BigInteger;

import javax.annotation.Generated;

import no.rightcloud.demo.author.jooq.tables.PmtInst;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PmtInstRecord extends TableRecordImpl<PmtInstRecord> implements Record9<BigInteger, BigInteger, String, String, BigDecimal, String, String, String, BigDecimal> {

    private static final long serialVersionUID = 2061952937;

    /**
     * Setter for <code>DEVDATA.PMT_INST.PMT_INST_ID</code>.
     */
    public void setPmtInstId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.PMT_INST_ID</code>.
     */
    public BigInteger getPmtInstId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INST.FK_PMT_INFO_ID</code>.
     */
    public void setFkPmtInfoId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.FK_PMT_INFO_ID</code>.
     */
    public BigInteger getFkPmtInfoId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INST.INSTRUCTION_ID</code>.
     */
    public void setInstructionId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.INSTRUCTION_ID</code>.
     */
    public String getInstructionId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INST.ENDTOENDID</code>.
     */
    public void setEndtoendid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.ENDTOENDID</code>.
     */
    public String getEndtoendid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INST.INSTD_AMT</code>.
     */
    public void setInstdAmt(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.INSTD_AMT</code>.
     */
    public BigDecimal getInstdAmt() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INST.INSTD_AMT_CCY</code>.
     */
    public void setInstdAmtCcy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.INSTD_AMT_CCY</code>.
     */
    public String getInstdAmtCcy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INST.CRDTR_NAME</code>.
     */
    public void setCrdtrName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.CRDTR_NAME</code>.
     */
    public String getCrdtrName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INST.CRDTR_ACCNT</code>.
     */
    public void setCrdtrAccnt(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.CRDTR_ACCNT</code>.
     */
    public String getCrdtrAccnt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DEVDATA.PMT_INST.CRDTR_ACCNT_IBAN</code>.
     */
    public void setCrdtrAccntIban(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_INST.CRDTR_ACCNT_IBAN</code>.
     */
    public BigDecimal getCrdtrAccntIban() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<BigInteger, BigInteger, String, String, BigDecimal, String, String, String, BigDecimal> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<BigInteger, BigInteger, String, String, BigDecimal, String, String, String, BigDecimal> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return PmtInst.PMT_INST.PMT_INST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return PmtInst.PMT_INST.FK_PMT_INFO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PmtInst.PMT_INST.INSTRUCTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PmtInst.PMT_INST.ENDTOENDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return PmtInst.PMT_INST.INSTD_AMT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PmtInst.PMT_INST.INSTD_AMT_CCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PmtInst.PMT_INST.CRDTR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PmtInst.PMT_INST.CRDTR_ACCNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return PmtInst.PMT_INST.CRDTR_ACCNT_IBAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getPmtInstId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getFkPmtInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getInstructionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEndtoendid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getInstdAmt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getInstdAmtCcy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCrdtrName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCrdtrAccnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getCrdtrAccntIban();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value1(BigInteger value) {
        setPmtInstId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value2(BigInteger value) {
        setFkPmtInfoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value3(String value) {
        setInstructionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value4(String value) {
        setEndtoendid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value5(BigDecimal value) {
        setInstdAmt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value6(String value) {
        setInstdAmtCcy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value7(String value) {
        setCrdtrName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value8(String value) {
        setCrdtrAccnt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord value9(BigDecimal value) {
        setCrdtrAccntIban(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtInstRecord values(BigInteger value1, BigInteger value2, String value3, String value4, BigDecimal value5, String value6, String value7, String value8, BigDecimal value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PmtInstRecord
     */
    public PmtInstRecord() {
        super(PmtInst.PMT_INST);
    }

    /**
     * Create a detached, initialised PmtInstRecord
     */
    public PmtInstRecord(BigInteger pmtInstId, BigInteger fkPmtInfoId, String instructionId, String endtoendid, BigDecimal instdAmt, String instdAmtCcy, String crdtrName, String crdtrAccnt, BigDecimal crdtrAccntIban) {
        super(PmtInst.PMT_INST);

        set(0, pmtInstId);
        set(1, fkPmtInfoId);
        set(2, instructionId);
        set(3, endtoendid);
        set(4, instdAmt);
        set(5, instdAmtCcy);
        set(6, crdtrName);
        set(7, crdtrAccnt);
        set(8, crdtrAccntIban);
    }
}
