/**
 * This class is generated by jOOQ
 */
package no.rightcloud.demo.author.jooq.tables;


import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import no.rightcloud.demo.author.jooq.Devdata;
import no.rightcloud.demo.author.jooq.Keys;
import no.rightcloud.demo.author.jooq.tables.records.PmtHeadRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PmtHead extends TableImpl<PmtHeadRecord> {

    private static final long serialVersionUID = -651365089;

    /**
     * The reference instance of <code>DEVDATA.PMT_HEAD</code>
     */
    public static final PmtHead PMT_HEAD = new PmtHead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PmtHeadRecord> getRecordType() {
        return PmtHeadRecord.class;
    }

    /**
     * The column <code>DEVDATA.PMT_HEAD.PMT_HEAD_ID</code>.
     */
    public final TableField<PmtHeadRecord, BigInteger> PMT_HEAD_ID = createField("PMT_HEAD_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>DEVDATA.PMT_HEAD.MSGID</code>.
     */
    public final TableField<PmtHeadRecord, String> MSGID = createField("MSGID", org.jooq.impl.SQLDataType.VARCHAR.length(35), this, "");

    /**
     * The column <code>DEVDATA.PMT_HEAD.CREATED</code>.
     */
    public final TableField<PmtHeadRecord, Date> CREATED = createField("CREATED", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>DEVDATA.PMT_HEAD.NR_OF_TRANS</code>.
     */
    public final TableField<PmtHeadRecord, BigDecimal> NR_OF_TRANS = createField("NR_OF_TRANS", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>DEVDATA.PMT_HEAD.CTRL_SUM</code>.
     */
    public final TableField<PmtHeadRecord, BigDecimal> CTRL_SUM = createField("CTRL_SUM", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>DEVDATA.PMT_HEAD.PARTY_INITIATOR</code>.
     */
    public final TableField<PmtHeadRecord, String> PARTY_INITIATOR = createField("PARTY_INITIATOR", org.jooq.impl.SQLDataType.VARCHAR.length(70), this, "");

    /**
     * The column <code>DEVDATA.PMT_HEAD.PARTY_ORG_ID</code>.
     */
    public final TableField<PmtHeadRecord, BigDecimal> PARTY_ORG_ID = createField("PARTY_ORG_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * Create a <code>DEVDATA.PMT_HEAD</code> table reference
     */
    public PmtHead() {
        this("PMT_HEAD", null);
    }

    /**
     * Create an aliased <code>DEVDATA.PMT_HEAD</code> table reference
     */
    public PmtHead(String alias) {
        this(alias, PMT_HEAD);
    }

    private PmtHead(String alias, Table<PmtHeadRecord> aliased) {
        this(alias, aliased, null);
    }

    private PmtHead(String alias, Table<PmtHeadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Devdata.DEVDATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PmtHeadRecord> getPrimaryKey() {
        return Keys.PMT_HEAD_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PmtHeadRecord>> getKeys() {
        return Arrays.<UniqueKey<PmtHeadRecord>>asList(Keys.PMT_HEAD_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHead as(String alias) {
        return new PmtHead(alias, this);
    }

    /**
     * Rename this table
     */
    public PmtHead rename(String name) {
        return new PmtHead(name, null);
    }
}
