/**
 * This class is generated by jOOQ
 */
package no.rightcloud.demo.pay.jooq.tables.records;


import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;

import javax.annotation.Generated;

import no.rightcloud.demo.pay.jooq.tables.PmtHead;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PmtHeadRecord extends UpdatableRecordImpl<PmtHeadRecord> implements Record7<BigInteger, String, Date, BigDecimal, BigDecimal, String, BigDecimal> {

    private static final long serialVersionUID = 2016092680;

    /**
     * Setter for <code>DEVDATA.PMT_HEAD.PMT_HEAD_ID</code>.
     */
    public void setPmtHeadId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_HEAD.PMT_HEAD_ID</code>.
     */
    public BigInteger getPmtHeadId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>DEVDATA.PMT_HEAD.MSGID</code>.
     */
    public void setMsgid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_HEAD.MSGID</code>.
     */
    public String getMsgid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DEVDATA.PMT_HEAD.CREATED</code>.
     */
    public void setCreated(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_HEAD.CREATED</code>.
     */
    public Date getCreated() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>DEVDATA.PMT_HEAD.NR_OF_TRANS</code>.
     */
    public void setNrOfTrans(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_HEAD.NR_OF_TRANS</code>.
     */
    public BigDecimal getNrOfTrans() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>DEVDATA.PMT_HEAD.CTRL_SUM</code>.
     */
    public void setCtrlSum(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_HEAD.CTRL_SUM</code>.
     */
    public BigDecimal getCtrlSum() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>DEVDATA.PMT_HEAD.PARTY_INITIATOR</code>.
     */
    public void setPartyInitiator(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_HEAD.PARTY_INITIATOR</code>.
     */
    public String getPartyInitiator() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DEVDATA.PMT_HEAD.PARTY_ORG_ID</code>.
     */
    public void setPartyOrgId(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>DEVDATA.PMT_HEAD.PARTY_ORG_ID</code>.
     */
    public BigDecimal getPartyOrgId() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigInteger, String, Date, BigDecimal, BigDecimal, String, BigDecimal> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigInteger, String, Date, BigDecimal, BigDecimal, String, BigDecimal> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return PmtHead.PMT_HEAD.PMT_HEAD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PmtHead.PMT_HEAD.MSGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return PmtHead.PMT_HEAD.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return PmtHead.PMT_HEAD.NR_OF_TRANS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return PmtHead.PMT_HEAD.CTRL_SUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PmtHead.PMT_HEAD.PARTY_INITIATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return PmtHead.PMT_HEAD.PARTY_ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getPmtHeadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMsgid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getNrOfTrans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getCtrlSum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPartyInitiator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getPartyOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHeadRecord value1(BigInteger value) {
        setPmtHeadId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHeadRecord value2(String value) {
        setMsgid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHeadRecord value3(Date value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHeadRecord value4(BigDecimal value) {
        setNrOfTrans(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHeadRecord value5(BigDecimal value) {
        setCtrlSum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHeadRecord value6(String value) {
        setPartyInitiator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHeadRecord value7(BigDecimal value) {
        setPartyOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PmtHeadRecord values(BigInteger value1, String value2, Date value3, BigDecimal value4, BigDecimal value5, String value6, BigDecimal value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PmtHeadRecord
     */
    public PmtHeadRecord() {
        super(PmtHead.PMT_HEAD);
    }

    /**
     * Create a detached, initialised PmtHeadRecord
     */
    public PmtHeadRecord(BigInteger pmtHeadId, String msgid, Date created, BigDecimal nrOfTrans, BigDecimal ctrlSum, String partyInitiator, BigDecimal partyOrgId) {
        super(PmtHead.PMT_HEAD);

        set(0, pmtHeadId);
        set(1, msgid);
        set(2, created);
        set(3, nrOfTrans);
        set(4, ctrlSum);
        set(5, partyInitiator);
        set(6, partyOrgId);
    }
}
