/**
 * This class is generated by jOOQ
 */
package no.rightcloud.demo.author.jooq;


import javax.annotation.Generated;

import no.rightcloud.demo.author.jooq.tables.Author;
import no.rightcloud.demo.author.jooq.tables.PmtInfo;
import no.rightcloud.demo.author.jooq.tables.PmtInst;
import no.rightcloud.demo.author.jooq.tables.PmtHead;
import no.rightcloud.demo.author.jooq.tables.SchemaVersion;


/**
 * Convenience access to all tables in DEVDATA
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DEVDATA.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>DEVDATA.PMT_HEAD</code>.
     */
    public static final PmtHead PMT_HEAD = PmtHead.PMT_HEAD;

    /**
     * The table <code>DEVDATA.PMT_INFO</code>.
     */
    public static final PmtInfo PMT_INFO = PmtInfo.PMT_INFO;

    /**
     * The table <code>DEVDATA.PMT_INST</code>.
     */
    public static final PmtInst PMT_INST = PmtInst.PMT_INST;

    /**
     * The table <code>DEVDATA.SCHEMA_VERSION</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = SchemaVersion.SCHEMA_VERSION;
}
